# Generated by Django 4.0.2 on 2022-03-01 15:46

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeName', models.CharField(max_length=120)),
                ('image', models.ImageField(default='default.jpg', upload_to='recipes_pics')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='The cost may not be less than 0.01 £')])),
                ('portion', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20, message='To many portions')])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(5, message='Please provide longer description')])),
                ('instruction', models.TextField(default='Step 1: ', validators=[django.core.validators.MinLengthValidator(10, message='Please provide longer instruction')])),
                ('cookingTime', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(120, message='The cooking time is too long')])),
                ('skillsLevel', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Difficult', 'Difficult')], max_length=30)),
                ('recipeCategory', models.CharField(choices=[('Picnic', 'Picnic'), ('Party', 'Party'), ('Dinner', 'Dinner'), ('Dessert', 'Dessert'), ('Other', 'Other')], default=('Other', 'Other'), max_length=30)),
                ('dateAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(default='Anonymous', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3000, message='To many calories')])),
                ('fat', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('-0.01'), message='Fat must not be less than 0'), django.core.validators.MaxValueValidator(500, message='Too much fat')])),
                ('carbohydrate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('-0.01'), message='Carbohydrate must not be less than 0'), django.core.validators.MaxValueValidator(500, message='Too much carbohydrate')])),
                ('fibre', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('-0.01'), message='Fibre must not be less than 0'), django.core.validators.MaxValueValidator(500, message='Too much fibre')])),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('-0.01'), message='Protein must not be less than 0'), django.core.validators.MaxValueValidator(500, message='Too much protein')])),
                ('salt', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('-0.01'), message='Salt must not be less than 0'), django.core.validators.MaxValueValidator(500, message='Too much salt')])),
                ('recipeName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipesApp.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=120)),
                ('recipeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipesApp.recipe')),
            ],
        ),
    ]
