# Generated by Django 4.0.2 on 2022-03-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesApp', '0003_rename_recipe name_ingredient_recipename_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe name',
            new_name='recipeName',
        ),
    ]
