# Generated by Django 4.0.2 on 2022-03-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesApp', '0004_rename_recipe name_recipe_recipename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipeName',
            field=models.CharField(max_length=120, verbose_name='recipe name'),
        ),
    ]
