# Generated by Django 4.0.2 on 2022-03-01 17:05

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipesApp', '0005_alter_recipe_recipename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cookingTime',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(120, message='The cooking time is too long')], verbose_name='cooking time'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dateAdded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipeCategory',
            field=models.CharField(choices=[('Picnic', 'Picnic'), ('Party', 'Party'), ('Dinner', 'Dinner'), ('Dessert', 'Dessert'), ('Other', 'Other')], default=('Other', 'Other'), max_length=30, verbose_name='recipe category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='skillsLevel',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Difficult', 'Difficult')], max_length=30, verbose_name='skills level'),
        ),
    ]
