# Generated by Django 4.0.2 on 2022-03-02 08:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesApp', '0006_alter_recipe_cookingtime_alter_recipe_dateadded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='The cost may not be less than 0.01 £')], verbose_name='total cost'),
        ),
    ]
