# Generated by Django 4.0.2 on 2022-03-11 21:30

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesApp', '0007_alter_recipe_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrient',
            name='calories',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000, message='To many calories')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cookingTime',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(1440, message='The cooking time is too long')], verbose_name='cooking time'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='The cost may not be less than 0.01 £'), django.core.validators.MaxValueValidator(Decimal('100.01'), message='The cost may not be greater than 100 £')], verbose_name='total cost'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, message='Please provide longer description')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instruction',
            field=models.TextField(max_length=100, validators=[django.core.validators.MinLengthValidator(10, message='Please provide longer instruction')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipeCategory',
            field=models.CharField(choices=[('Picnic', 'Picnic'), ('Party', 'Party'), ('Dinner', 'Dinner'), ('Dessert', 'Dessert'), ('Drink', 'Drink'), ('Other', 'Other')], default=('Other', 'Other'), max_length=30, verbose_name='recipe category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipeName',
            field=models.CharField(max_length=150, verbose_name='recipe name'),
        ),
    ]
