# Generated by Django 4.0.2 on 2022-03-11 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesApp', '0008_alter_nutrient_calories_alter_recipe_cookingtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instruction',
            field=models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(10, message='Please provide longer instruction')]),
        ),
    ]
