# Generated by Django 4.0.2 on 2022-03-11 21:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesApp', '0009_alter_recipe_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrient',
            name='calories',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10000, message='To many calories')]),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='carbohydrate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-0.01'), message='Carbohydrate must not be less than 0'), django.core.validators.MaxValueValidator(500, message='Too much carbohydrate')]),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-0.01'), message='Fat must not be less than 0'), django.core.validators.MaxValueValidator(500, message='Too much fat')]),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='fibre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-0.01'), message='Fibre must not be less than 0'), django.core.validators.MaxValueValidator(500, message='Too much fibre')]),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-0.01'), message='Protein must not be less than 0'), django.core.validators.MaxValueValidator(500, message='Too much protein')]),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='salt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-0.01'), message='Salt must not be less than 0'), django.core.validators.MaxValueValidator(500, message='Too much salt')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instruction',
            field=models.TextField(max_length=5000, validators=[django.core.validators.MinLengthValidator(10, message='Please provide longer instruction')]),
        ),
    ]
