# Generated by Django 4.0.2 on 2022-03-18 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesApp', '0010_alter_nutrient_calories_alter_nutrient_carbohydrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(3, message='Please provide longer ingredient description')]),
        ),
    ]
