# Generated by Django 4.0.2 on 2022-03-21 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesApp', '0011_alter_ingredient_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.MinLengthValidator(3, message='Please provide longer ingredient description')]),
        ),
    ]
