# Generated by Django 4.0.2 on 2022-03-21 23:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesApp', '0012_alter_ingredient_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cookingTime',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(1440, message='The cooking time is too long')], verbose_name='cooking time(mins)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='The cost may not be less than 0.01 £'), django.core.validators.MaxValueValidator(Decimal('100.01'), message='The cost may not be greater than 100 £')], verbose_name='total cost(£)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default.jpg', max_length=250, upload_to='recipes_pics', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'webp', 'tiff', 'gif', 'jpeg', 'bmp', 'ico', 'tif'], message='check the file type')]),
        ),
    ]
