# Generated by Django 4.0.2 on 2022-03-22 10:50

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipesApp', '0013_alter_recipe_cookingtime_alter_recipe_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrient',
            name='carbohydrate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-0.01'), message='Carbohydrate must not be less than 0'), django.core.validators.MaxValueValidator(1000, message='Too much carbohydrate')]),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-0.01'), message='Fat must not be less than 0'), django.core.validators.MaxValueValidator(1000, message='Too much fat')]),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-0.01'), message='Protein must not be less than 0'), django.core.validators.MaxValueValidator(1000, message='Too much protein')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cookingTime',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(1440, message='The cooking time is too long')], verbose_name='Cooking time (mins)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='The cost may not be less than 0.01 £'), django.core.validators.MaxValueValidator(Decimal('100.01'), message='The cost may not be greater than 100 £')], verbose_name='Total cost (£)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dateAdded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(max_length=120, validators=[django.core.validators.MinLengthValidator(5, message='Please provide longer description')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default.jpg', max_length=250, upload_to='recipes_pics', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'webp', 'tiff', 'gif', 'jpeg', 'bmp', 'ico', 'tif'], message='Specify a valid file type')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipeCategory',
            field=models.CharField(choices=[('Picnic', 'Picnic'), ('Party', 'Party'), ('Dinner', 'Dinner'), ('Dessert', 'Dessert'), ('Drink', 'Drink'), ('Other', 'Other')], default=('Other', 'Other'), max_length=30, verbose_name='Recipe category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipeName',
            field=models.CharField(max_length=150, verbose_name='Recipe name'),
        ),
    ]
