# Generated by Django 4.0.2 on 2022-03-22 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesApp', '0014_alter_nutrient_carbohydrate_alter_nutrient_fat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='portion',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20, message='To many portions'), django.core.validators.MinValueValidator(1, message='Portion must be more than 0')]),
        ),
    ]
