# Generated by Django 4.0.2 on 2022-03-29 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesApp', '0015_alter_recipe_portion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(3, message='Please provide longer ingredient description')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default.jpg', max_length=250, upload_to='recipes_pics', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'webp', 'tiff', 'gif', 'jpeg', 'bmp', 'ico', 'tif', 'svgz', 'svg', 'pjp', 'xbm', 'jfif', 'pjpeg', 'avif'], message='Specify a valid file type')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='skillsLevel',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Difficult', 'Difficult')], default=('Easy', 'Easy'), max_length=30, verbose_name='skills level'),
        ),
    ]
